### ISSUE TITLE
The MinioPolicyBinding object does not get deleted when removing MinioUser, MinioPolicy and MinioPolicyBinding objects from a cluster

### ISSUE THREAD

**Issue by steinwelberg** [benfiola/minio-operator-ext#14]
The MinioPolicyBinding CR does not get deleted when we remove the MinioUser, MinioPolicy and MinioPolicyBinding objects from a cluster at the same time.

Deleting the policy binding fails with the following error (logs from the operator):
```
2024-09-04 13:43:47,125 - INFO - minio_operator_ext.operator - delete:infra-minio/ci-e0eb02dd-typescript-react-template started                                                                                                                                              │
│ 2024-09-04 13:43:47,134 - INFO - minio_operator_ext.operator - delete:infra-minio/ci-e0eb02dd-typescript-react-template-policy started                                                                                                                                       │
│ 2024-09-04 13:43:47,143 - INFO - minio_operator_ext.operator - delete:infra-minio/ci-e0eb02dd-typescript-react-template-policy-binding started                                                                                                                               │
│ 2024-09-04 13:43:47,213 - INFO - minio_operator_ext.operator - delete:infra-minio/ci-e0eb02dd-typescript-react-template started                                                                                                                                              │
│ 2024-09-04 13:43:47,317 - INFO - minio_operator_ext.operator - delete:infra-minio/ci-e0eb02dd-typescript-react-template completed                                                                                                                                            │
│ 2024-09-04 13:43:47,415 - ERROR - minio_operator_ext.operator - delete:infra-minio/ci-e0eb02dd-typescript-react-template-policy failed with retryable error: admin request failed; Status: 400, Body: {"Code":"XMinioIAMPolicyInUse","Message":"The policy cannot be removed │
│ , as it is in use","Resource":"/minio/admin/v3/remove-canned-policy","RequestId":"17F20E636C183861","HostId":"569a2c2b6fe6f180002dfb8bb719e75853115b62c50874ff56f4c016dde8d1b8"}                                                                                             │
```

For completeness all delete resource logs are included. Btw, both the bucket and the user have the name `ci-e0eb02dd-typescript-react-template`.

We also noticed that the first time the policy gets deployed, the same error is triggered.

**Comment by benfiola** [comment]
> We also noticed that the first time the policy gets deployed, the same error is triggered.

On policy binding creation, if the resource fails to create because a user/group/policy doesn't exist - it should retry until success.  In your case, did this happen?

> The MinioPolicyBinding CR does not get deleted when we remove the MinioUser, MinioPolicy and MinioPolicyBinding objects from a cluster at the same time.

This shouldn't happen!  Taking a look.

**Comment by benfiola** [comment]
I've put in the [following code](https://github.com/benfiola/minio-operator-ext/pull/15) that addresses the issues you were facing re: _MinioPolicyBinding_ resource deletion.

Let me know if the latest docker image resolves your issues!

**Comment by steinwelberg** [comment]
> > We also noticed that the first time the policy gets deployed, the same error is triggered.
> 
> On policy binding creation, if the resource fails to create because a user/group/policy doesn't exist - it should retry until success. In your case, did this happen?
> 
> > The MinioPolicyBinding CR does not get deleted when we remove the MinioUser, MinioPolicy and MinioPolicyBinding objects from a cluster at the same time.
> 
> This shouldn't happen! Taking a look.

Yeah, on resource creation, the problem resolves itself! Just wanted to mention it here to be complete. Great. Will have a look!

**Comment by steinwelberg** [comment]
Alright, I have verified that it works as expected! Thanks for the quick response and fix! 💪
