### ISSUE TITLE
Refactor operator

### ISSUE THREAD

**Issue by benfiola** [benfiola/minio-operator-ext#16]
Currently, there are a few things about the operator I don't like - even though it works (at least for my personal use case and the features my development environment test for).

### Python to Golang
minio-operator-ext is written in python because I've been a python developer for about a decade and find the language comfortable.  However, lately, I've been writing a lot of golang and I'm finding that I like it a whole lot more than python.  I enjoy its pragmatism, its simplicity and its ability to compile (and cross-compile!) executables with ease.  Plus, compiling my code into executables produces tiny docker images - and that's been great, shaving down image sizes by two orders of magnitude.

Finally, I read this [comment](https://www.reddit.com/r/kubernetes/comments/1dge5qk/comment/l8qbbll) on reddit.  minio-operator-ext does _not_ have this problem because I use an embedded spec stored in the status field as a source of truth.  However, I do accept that this is a flaw in kopf and a refactor to golang would fundamentally move me off of the framework.  

The goal here is to refactor the operator to golang.  While I'd love to avoid boilerplate, there's a bit of momentum around using _kubebuilder_ to generate project scaffolds (with added scaffold upgrade support as of 9/2023) - so I'll probably utilize _kubebuilder_ so that this code-base will likely be familiar to anyone who has worked with golang controllers before.

###  Process optimizations
I personally think the operator can be improved as it pertains to resource discovery.  I think that:

* The operator can better 'discover' existing `Tenant` resources in advance
* 'Discover' existing resources on each `Tenant` (e.g., enumerating the buckets, users, policies, etc. that exist)
* With the above information, it can better validate (- in advance) whether a tenant exists, is connectable, and whether a resource conflict might exist (e.g., trying to create a _MinioBucket_ when someone might have externally created a bucket with the same name).
* (Optionally) Adopt validating webhook controllers to prevent the creation of uncreatable resources.  I've been meaning to do this for a while - but there isn't a great development story around these (often requiring creating tunnels into the cluster to an external in-development webhook) - and I've never really liked that.

**Comment by benfiola** [comment]
For now, this effort will be contained in the `go` branch.

**Comment by benfiola** [comment]
Over the next few days, I anticipate that I'll integrate these changes into `dev` and `main`.

Here's what to expect:

* New language.  This is now a golang project.  It should hopefully be faster, and the docker images should hopefully be smaller.
* Different log output.  As part of the transition, I've adopted the `slog` package which produces structured logs - changing the formatting of the log output.  However, I've also made logging more consistent to hopefully help in tracing issues that might arise.
* Added e2e tests.  Previously, I'd manually run through test cases I thought were important to catch regressions.  Now, they should hopefully be captured via automation.
* Changed the `MinioUser` CRD to add an additional status field for `secretKeyRef` tracking.  More about this in the following bullet point.
* Better reconciliation.  Kubernetes objects will periodically reconcile (- even when the underlying kubernetes spec hasn't changed).  Remote resources will be recreated if we detect that they've been deleted.  `MinioPolicyBinding` and `MinioGroupBinding` objects will gracefully detach/attach on update.  `MinioUser` objects will detect when their `secretKeyRef` has changed, and will update their secret key accordingly.  `MinioPolicy` objects will generally stay in sync with their remote counterparts.
* Removed event publishing.  Really, this just means one less set of RBAC permissions to maintain.  If events are needed in the future, I can add them back - I just haven't figured out a good, consistent case for using them (vs. logging).

**Comment by steinwelberg** [comment]
I assume the `kopf.zalando.org/last-handled-configuration` annotation can also be removed?

**Comment by benfiola** [comment]
Thank YOU for using the operator!  🥳 

Great catch - and you're right, there's no need for that annotation once migrated onto v2 of the operator.  I'll add it to the above comment.

**Comment by benfiola** [comment]
Code has been merged into `main` as version `2.0.0`.
