### ISSUE TITLE
Helm chart for deployment

### ISSUE THREAD

**Issue by nogweii** [benfiola/minio-operator-ext#19]
I might take a stab at this soon, but wanted to ask if you had ideas on this already.

**Comment by benfiola** [comment]
I haven't - but think it'd be cool.  While I've played with (and have been a client of) helm, I've never written a chart intended to be used by others.   If you'd like to give it a shot, I'd be more than happy to review a PR.  Otherwise, I can give it a try myself - either works!

**Comment by steinwelberg** [comment]
Is it an idea to separate the crds from the operator itself? This pattern is used in multiple other operators as well, given that Helm is not able to upgrade or delete crds if you put them in the `crds` folder. See also: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

**Comment by benfiola** [comment]
> Is it an idea to separate the crds from the operator itself? This pattern is used in multiple other operators as well ...

Unfortunately, I purely rely upon `helm template`.  Despite this, I've seen helm chart authors approach this problem from three different angles:

* Use helm's CRD management (i.e., helm will install your CRDs for you - but will not update them)
* Use a separate `values.yaml` key to manage CRDs.
* Bake CRD management into the operator itself

I don't personally have a strong opinion about which approach we take (- though I'd prefer CRD management to be user initiated vs. controlled by the operator).  Is there an approach that either of you would prefer?

**Comment by steinwelberg** [comment]
I don't like it that Helm cannot update the CRDs. So, if 2 charts is not a solution then in that case I would prefer going the separate key route in the `values.yaml` as that does give you control to install the CRDs separately from the operator. It would then be required to be able to only install the crds though and not the operator itself.

**Comment by steinwelberg** [comment]
With separate the CRDs from the operator I mean that we create a separate Helm chart for the CRDs. See for example: https://artifacthub.io/packages/helm/snowplow-devops/cert-manager-crds.

IMO this is the cleanest solution.

**Comment by benfiola** [comment]
Whoops - looks like merging the related branch accidentally closed this issue.  Anyhow, with a little bit of work (and @nogweii's charts), I was able to set up a helm repository.

The repo is located at [https://benfiola.github.io/minio-operator-ext/charts](https://benfiola.github.io/minio-operator-ext/charts) - and both development and release charts should be published as of version `2.2.0`.

Give it a shot and let me know if you run into any issues!

**Comment by nogweii** [comment]
@benfiola I'm trying to deploy the helm chart and I'm getting an error from Kubernetes:

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/operator": stat /operator: no such file or directory: unknown
```

And inspecting the 2.2.0 tag (using `dive` and `docker image inspect`) the image only shows 1 layer - the base distroless layer. No operator binary to be found. Was there a hiccup in the docker release process?

**Comment by benfiola** [comment]
:grimacing: - yep, I goofed when I modified the docker image publishing workflow.  

Turns out `docker buildx build ... --output type=tar,...` does _not_ do what I thought it did.  Loading the resulting tar and publishing it does indeed produce a bad image.  Will work on fixing this ASAP - thanks for the heads up!

**Comment by benfiola** [comment]
Alright, the new versions are building, but things should be fixed as of version `2.2.1`.  Let me know if you run into any issues with the updated helm charts!

**Comment by steinwelberg** [comment]
I haven't gotten around to migrating to the helm charts from the repo yet. Once I have done so, I will give a heads up if all is fine :-).

**Comment by steinwelberg** [comment]
The charts work like a charm! They were a drop-in replacement for the ones we had temporarily constructed.

**Comment by benfiola** [comment]
yeah!  i migrated my infrastructure-as-code project to use these charts and it was very convenient.

thanks again for the contribution @nogweii - and thanks for verifying that things look good @steinwelberg!  🥳 

am going to close this issue out, feel free to open new issues for any problems you run into.
